import { AiIntent } from "@/lib/ai/types";

export const AI_INTENTS: AiIntent[] = [
  "TOTAL_STUDENTS",
  "TOTAL_ACTIVE_ENROLLMENTS",
  "TOTAL_OVERDUE_PAYMENTS",
  "TOTAL_PENDING_PAYMENTS",
  "MONTHLY_REVENUE",
  "TOP_COURSES",
  "UPCOMING_EVENTS",
  "LIST_OVERDUE_STUDENTS",
  "GENERATE_MONTHLY_PAYMENTS",
  "MARK_PAYMENT_PAID",
  "CHAT",
];